name       : minuet
version    : 17.12.1
release    : 6
source     :
    - https://cdn.download.kde.org/stable/applications/17.12.1/src/minuet-17.12.1.tar.xz : 87f00f81ee0f7e76e7a075554bd9ef44dfe1a09fc5845bd39e10f23d200ef4f8
license    :
    - GPL-2.0
    - GFDL-1.3
component  : multimedia.audio
optimize   : lto
summary    : KDE software for music education
description: |
    Minuet aims at supporting students and teachers in many aspects of music education, such as ear training, first-sight reading, solfa, scales, rhythm, harmony, and improvisation. Minuet makes extensive use of MIDI capabilities to provide a full-fledged set of features regarding volume, tempo, and pitch changes, which makes Minuet a valuable tool for both novice and experienced musicians.
builddeps  :
    - pkgconfig(fluidsynth)
    - pkgconfig(gl)
    - pkgconfig(Qt5Qml)
    - pkgconfig(Qt5QuickControls2)
    - pkgconfig(Qt5Svg)
    - extra-cmake-modules
    - kcoreaddons-devel
    - kcrash-devel
    - kdoctools-devel
    - ki18n-devel
rundeps    :
    - qt5-quickcontrols2
    - qt5-svg
setup      : |
    %cmake .
build      : |
    %make
install    : |
    %make_install
