name       : minuet
version    : 19.12.1
release    : 35
source     :
    - https://cdn.download.kde.org/stable/release-service/19.12.1/src/minuet-19.12.1.tar.xz : 735b340f9f0d6ee09c2c6aa76061282da6bd921f8b77683c53311731a77edff1
homepage   : https://kde.org/applications/education/org.kde.minuet
license    :
    - GPL-2.0-or-later
    - GFDL-1.3-or-later
component  : multimedia.audio
summary    : KDE software for music education
description: |
    Minuet aims at supporting students and teachers in many aspects of music education, such as ear training, first-sight reading, solfa, scales, rhythm, harmony, and improvisation. Minuet makes extensive use of MIDI capabilities to provide a full-fledged set of features regarding volume, tempo, and pitch changes, which makes Minuet a valuable tool for both novice and experienced musicians.
builddeps  :
    - pkgconfig(fluidsynth)
    - pkgconfig(Qt5Qml)
    - pkgconfig(Qt5QuickControls2)
    - pkgconfig(Qt5Svg)
    - extra-cmake-modules
    - kcoreaddons-devel
    - kcrash-devel
    - kdoctools-devel
    - ki18n-devel
rundeps    :
    - qt5-quickcontrols2
    - qt5-svg
setup      : |
    %cmake_ninja
build      : |
    %ninja_build
install    : |
    %ninja_install
