name       : minuet
version    : 20.04.0
release    : 38
source     :
    - https://cdn.download.kde.org/stable/release-service/20.04.0/src/minuet-20.04.0.tar.xz : 143c338fe2efeac650634dd4e5c34bd4d194330f0820deee5bd8993a5a7c0c72
homepage   : https://kde.org/applications/education/org.kde.minuet
license    :
    - GPL-2.0-or-later
    - GFDL-1.3-or-later
component  : multimedia.audio
summary    : KDE software for music education
description: |
    Minuet aims at supporting students and teachers in many aspects of music education, such as ear training, first-sight reading, solfa, scales, rhythm, harmony, and improvisation. Minuet makes extensive use of MIDI capabilities to provide a full-fledged set of features regarding volume, tempo, and pitch changes, which makes Minuet a valuable tool for both novice and experienced musicians.
builddeps  :
    - pkgconfig(fluidsynth)
    - pkgconfig(Qt5Qml)
    - pkgconfig(Qt5QuickControls2)
    - pkgconfig(Qt5Svg)
    - extra-cmake-modules
    - kcoreaddons-devel
    - kcrash-devel
    - kdoctools-devel
    - ki18n-devel
rundeps    :
    - qt5-quickcontrols2
    - qt5-svg
setup      : |
    %cmake_ninja
build      : |
    %ninja_build
install    : |
    %ninja_install
