name       : minuet
version    : 21.12.0
release    : 59
source     :
    - https://cdn.download.kde.org/stable/release-service/21.12.0/src/minuet-21.12.0.tar.xz : 861348bdcec37c45f94b29966962dabf2a2948cf1341e466a290c0ba5ce7f465
homepage   : https://kde.org/applications/education/org.kde.minuet
license    :
    - GPL-2.0-or-later
    - GFDL-1.3-or-later
component  : multimedia.audio
summary    : KDE software for music education
description: |
    Minuet aims at supporting students and teachers in many aspects of music education, such as ear training, first-sight reading, solfa, scales, rhythm, harmony, and improvisation. Minuet makes extensive use of MIDI capabilities to provide a full-fledged set of features regarding volume, tempo, and pitch changes, which makes Minuet a valuable tool for both novice and experienced musicians.
builddeps  :
    - pkgconfig(fluidsynth)
    - pkgconfig(Qt5Quick)
    - pkgconfig(Qt5QuickControls2)
    - pkgconfig(Qt5Svg)
    - kcoreaddons-devel
    - kcrash-devel
    - kdoctools-devel
    - ki18n-devel
rundeps    :
    - qt5-quickcontrols2
setup      : |
    %cmake_ninja
build      : |
    %ninja_build
install    : |
    %ninja_install

    #remove docs
    rm -rf $installdir/usr/share/doc
